### ISSUE TITLE
Dataframe with numeric values

### ISSUE THREAD

**Issue by peterrhysstrong** [g-walley/cegpy#19]
Currently the code cannot generate figures for data frames with numeric values.

**Comment by g-walley** [comment]
@peterrhysstrong I can't remember if I fixed this. Could you check if it works now?

**Comment by ashenvi10** [comment]
@peterrhysstrong Hi Peter, we've just checked that this works. I'm going to close this issue now. If the problem persists, please reopen this issue and provide a minimum reproducible example (dataset and code) for the issue.

**Comment by peterrhysstrong** [comment]
Noticed a bug related to this issue when adding in sampling zero paths. Using the following dataset:
[Asym.csv](https://github.com/g-walley/cegpy/files/7943460/Asym.csv)


`import pandas as pd
from cegpy.src.cegpy.trees import staged 
data = pd.read_csv("datasets/Asym.csv")
missing_paths=[('0', '1', '1', '1'), ('1', '0', '1', '1'), ('0', '1', '0', '1')]
st = staged.StagedTree(data,sampling_zero_paths=missing_paths)`

I am fairly sure this is related as adding the following line runs fine 

`data=data.astype(string)
`

**Comment by ashenvi10** [comment]
Thanks @peterrhysstrong, We'll have a look.
