### ISSUE TITLE
To Do 23/07/2021: Peter

### ISSUE THREAD

**Issue by ashenvi10** [g-walley/cegpy#2]
- [x] Download package from Pypi after Gareth uploads it
- [x] Run pytest locally
- [x] Run the code with different datasets and time it

**Comment by ashenvi10** [comment]
@peterrhysstrong  How is this going? Please add your reply to this issue so we can keep track. Thanks!

**Comment by peterrhysstrong** [comment]
I have all the code ready to time it in python and R. I am waiting for for some of the other issues raised to be fixed as I have been getting errors based on issues I have raised based on unobserved paths

**Comment by ashenvi10** [comment]
@peterrhysstrong Could you please update on this issue? I believe we aren't timing the datasets anymore?
