### ISSUE TITLE
Output Dot File

### ISSUE THREAD

**Issue by g-walley** [g-walley/cegpy#27]
Add Dot file output from pdp package. This gives the user the flexibility to use any number of Dot compatible packages for producing graphs in whatever style they like.

**Comment by Kaasiak** [comment]
I did a little bit of research concerning this issue. I came to the conclusion that embedding dot graphs within latex documents may be beyond the scope of the cegpy package. It is a more complex problem and the existing solutions are:
1. Include the PDFs/PNGs generated by Graphviz/dot in the document by simply using `\includegraphics`-> problems: no possibility to use TeX conde in the graph, graphs can appear out of style with other figures in the document
2. Use `dot2tex` to convert the Gprahviz/dot graphs to TeX/TikZ -> this is what I did for my report on CEGs, yet including this possibility in the cegpy package would involve adding an extra dependency on `dot2tex` which is not the most reliable. From my experience, it involved plenty of manual tuning to choose parameters for the font size, node sizes, etc. that would be compatible with the rest of the final TeX document. 

In the first place, I thought about including the dot2tex converter within the cegpy package, but now I consider it to be redundant. If the user wants TikZ output they may just export the graph in the .dot format and play with the dot2tex converter separately. 

My suggestion is to just add the functionality of returning the graph as the dot instance generated with pdp. This would allow the user to manipulate the graph freely. Manually add extra edges, change colours of nodes, style of edges etc. Currently the `_generate_pdp_graph()` function within `event.py` does exactly this, but it is for internal use only. We could perhaps just add a wrapper for returning the dot graph. Thoughts?

**Comment by g-walley** [comment]
Thanks for looking into this and providing a summation of the options.
I like the option of producing the dot file. Gives more flexibility to the user, and reduces the code we need to maintain. Good idea! 
You can add the change to both EventTree() and ChainEventGraph().
