### ISSUE TITLE
User defined colour palette 

### ISSUE THREAD

**Issue by g-walley** [g-walley/cegpy#28]
User might like to define colour palette themselves

**Comment by g-walley** [comment]
@Kaasiak We found that the change you had made for this didn't quite work. It was giving each node a colour but _not_ according to which stage it was in. We fixed that to ensure the colour is given based on stage.

Also, we think it should be the case that an error is thrown rather than a warning if you provide fewer colours than there are stages. We couldn't see a situation where you would want nodes that are in different stages to end up with the same colour. If you disagree with this or have a use case where that might be the case, please let us know. We could add a flag the user sets to ignore that error.

Thanks!

**Comment by Kaasiak** [comment]
I adopted the strategy of recycling the colours as a similar approach was implemented in the `stagedtrees` package. Though, as I remember, in `stagedtrees` not even a warning was thrown. This was rather confusing, so I figured out that a warning would be appropriate. I think that in the end an error with a flag for ignoring might be the best solution.

Thanks a lot for investigating this and correcting my silly error.

**Comment by g-walley** [comment]
No worries! Thanks for contributing :) We found the bug whilst doing something else, so I hadn't noticed it when I reviewed your code!

**Comment by Kaasiak** [comment]
I was experimenting with the cegpy package and noticed that the current implementation requires more colours than actually needed. `len(merged_situations)` includes in the count stages with only a single situation. These are ultimately coloured in light grey, so there is no need to take them into account.

**Comment by ashenvi10** [comment]
Thanks @Kaasiak, we'll get this fixed soon!

**Comment by ashenvi10** [comment]
Apologies, I see you have already done this and it's been merged. Thanks again :)
