### ISSUE TITLE
Type error: generating figures

### ISSUE THREAD

**Issue by peterrhysstrong** [g-walley/cegpy#31]
Type error when generating figures for Event/staged trees created from data frames with numeric elements in them.

**Comment by ashenvi10** [comment]
Hi @peterrhysstrong is this the same as issue #19? We have fixed this now. So I am closing this issue. If the problem persists, please reopen this issue and provide a minimum reproducible example (dataset and code) for the issue.

**Comment by ashenvi10** [comment]
@all-contributors please add @peterrhysstrong  for Code, Bug Reports, Examples, and Tests
