### ISSUE TITLE
Include all unobserved paths

### ISSUE THREAD

**Issue by peterrhysstrong** [g-walley/cegpy#32]
Currently there is no way to create an event tree that includes all unobserved paths, without specifying each path individually

**Comment by ashenvi10** [comment]
@peterrhysstrong Hi Peter, we're not sure that this is an essential feature for the first release. I would recommend writing a script to fix this issue in your experiments such that you follow the steps below:

1. Create an event tree with the original dataset
2. Check whether an element from the sample space of each variable appears on each path. If not, add that path as a tuple to a separate list of unobserved paths.
3. Create a new event tree with the original dataset by supplying the list of unobserved paths as the optional argument of sampling_zero_paths.

This should resolve your issue. 

I'm going to leave this issue open until you reply. If you still want to add this as a feature for the current release, I will assign the job to you and we can give you guidance over how this can be added to the code. Hope this is okay.

**Comment by peterrhysstrong** [comment]
@ashenvi10 I think this is essential part of allowing the user to use stratified CEGs without manually adding each path. 

Happy to work on adding this code to the release of the code but would need some guidance in particular how to add labelled zero-weighted edges to a created Event tree/ staged tree.

**Comment by ashenvi10** [comment]
@peterrhysstrong My thoughts are that if there are too many paths with sampling zeros such that adding them all manually is difficult then the dataset could be either too small for a meaningful analysis (lots of zero edges) or perhaps many of these could be structural zeros. Hence, not sure it is essential for the use of stratified CEGs with this package. 

However, happy to help you work on this code. You would add the sampling zero path as key within the data dictionary and map it to 0. To be honest, I'm not sure what you mean by adding labelled zero-weighted edges; have I interpreted your question correctly?

**Comment by ashenvi10** [comment]
@peterrhysstrong Any progress on this issue or is there any way Gareth or I could help?
Could you also update whether we are still looking to resolve this issue for the v1.0 milestone?

**Comment by peterrhysstrong** [comment]
I have written some code that is able to add in all missing paths. However I have not added this in as part of the package. I am happy to try and do so but would need some guidance.

**Comment by peterrhysstrong** [comment]
``` python
	uniques = [list(set(data[k])) for k in data.columns]
	all_paths=list(product(*uniques))
	paths=data.drop_duplicates().values.tolist()
	all_paths_list = [list(ele) for ele in all_paths]

	Length_of_paths=len(all_paths_list[0])
	missing_paths=[]
	for i in range(0,Length_of_paths):
		temp_paths = [path[:Length_of_paths-i] for path in paths]
		new_missing_paths_list=[path[:Length_of_paths-i] for path in all_paths_list if path[:Length_of_paths-i] not in temp_paths]
		if new_missing_paths_list !=[]:
			missing_paths=[*new_missing_paths_list,*missing_paths]
	missing_paths=list(tuple(x) for x in missing_paths)
	missing_paths=sorted(missing_paths, key=len)
```

**Comment by g-walley** [comment]
@peterrhysstrong 
I have done some unit testing. Could you check it works like you expect when interacting with missing values?
I'll be honest, looking at a lot of datasets, it looks like it won't work very well. So I hope it does what you want!
