### ISSUE TITLE
Floret with one edge Issue 

### ISSUE THREAD

**Issue by peterrhysstrong** [g-walley/cegpy#33]
When we have a floret with only one outgoing edge, such as s14, s16, s18, s20 in the attached staged tree, they should all be in the same stage (in the attached tree s14 isnt). I think it should be hard coded for situations when there is one potential outcomes and the edge label is the same that those stages should be in the same stage.

[Titanic.pdf](https://github.com/g-walley/cegpy/files/7624253/Titanic.pdf)

**Comment by g-walley** [comment]
@peterrhysstrong is this still broken in release 0.2?

**Comment by g-walley** [comment]
Addressed, and merged to dev branch. Could you confirm it is fixed for your dataset? We replicated it with another dataset on our end.

**Comment by peterrhysstrong** [comment]
Yes this works for the dataset which was causing an issue
