### ISSUE TITLE
Issue with calculate_AHC_transitions and sampling zero paths in dev branch 

### ISSUE THREAD

**Issue by peterrhysstrong** [g-walley/cegpy#46]
The following code raises a type error  when calculating the AHC transitions 

`TypeError: 'Fraction' object is not iterable`

``` python
df = pd.read_excel("data/medical_dm_modified.xlsx")
falls_st = StagedTree(dataframe=df,sampling_zero_paths=[('Blast','Experienced', 'Easy','Blast', 'extra')])
falls_st.calculate_AHC_transitions()
falls_st.create_figure("st_fig_extra_paths.pdf")
```

**Comment by peterrhysstrong** [comment]
Similarly when adding in missing paths that include all of the outcomes of a floret such as in the following example

[Titanic.csv](https://github.com/g-walley/cegpy/files/7943741/Titanic.csv)

import pandas as pd
from cegpy.src.cegpy.trees import staged
data = pd.read_csv("datasets/Titanic.csv")
missing_paths=[('Crew', 'Female', 'Child'), ('Crew', 'Female', 'Child', 'No'), ('Crew', 'Female', 'Child', 'Yes')]
st = staged.StagedTree(data,sampling_zero_paths=missing_paths)
st.calculate_AHC_transitions()

**Comment by g-walley** [comment]
@peterrhysstrong I have applied a fix to dev. Could you test it has solved it for you?
