### ISSUE TITLE
Error in displaying the CEG graph

### ISSUE THREAD

**Issue by kasia-kobalczyk** [g-walley/cegpy#74]
https://github.com/g-walley/cegpy/blob/b39c9c86faaf21ccabcd37d9a88713bfbbc98baf/src/cegpy/graphs/ceg.py#L282-L283

Edge probabilities are stored as Fractions. This generates the following error:

`[TypeError: unsupported format string passed to Fraction.__format__]()`

**Comment by Kaasiak** [comment]
I realised that this was an issue only if you forgot to run `.generate()` first. 
Now that the leg generating function is called by default this is not a problem.
