### ISSUE TITLE
Add a warning for creating a ceg graph without calling `.generate()`

### ISSUE THREAD

**Issue by Kaasiak** [g-walley/cegpy#79]
Add a warning / error for the user when trying to create a ceg graph without running `.generate()` first.

**Comment by ashenvi10** [comment]
@Kaasiak I have changed the default of the generate argument to True for the CEG class. I think it's more intuitive that way because if I initiate an object in the CEG class, I would personally assume that it initialises a CEG. Hope that's okay!
